# Generated by Django 4.2.11 on 2024-08-04 01:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('arrengement', models.CharField(max_length=255)),
                ('employment', models.CharField(max_length=255)),
                ('date_posted', models.DateField()),
                ('about', models.TextField()),
                ('careers', models.ManyToManyField(related_name='jobs', to='dashboard.career')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('student_career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.studentcareer')),
            ],
        ),
    ]
